name: 'Publish'

on:
  push:
    branches: [ master ]

  milestone:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            packages/*/dist/*
            packages/*/bundles/*

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - 'jill-e2e'
          - '@jujulego/jill'
          - '@jujulego/jill-core'
          - '@jujulego/yarn-plugin-jill'

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn workspace ${{ matrix.package }} lint

  tests:
    runs-on: ubuntu-latest
    needs: [ build ]

    strategy:
      fail-fast: false

      matrix:
        include:
          - name: 'jill'
            package: '@jujulego/jill'
            workspace: 'packages/cli'

          - name: 'jill-core'
            package: '@jujulego/jill-core'
            workspace: 'packages/core'

          - name: 'yarn-plugin-jill'
            package: '@jujulego/yarn-plugin-jill'
            workspace: 'packages/yarn-plugin'

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: packages

      - name: Test
        run: yarn workspace ${{ matrix.package }} test

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}-coverage
          path: ${{ matrix.workspace }}/coverage

  e2e-tests:
    runs-on: ${{ matrix.os }}
    needs: [ build ]

    strategy:
      fail-fast: false

      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: packages

      - name: Test
        run: yarn e2e
        env:
          FORCE_COLOR: 1

  publish:
    runs-on: ubuntu-latest
    environment: npm
    needs: [ lint, tests, e2e-tests ]

    permissions:
      actions: write
      contents: write

    steps:
      - name: Publish only the latest commit
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2.3.4
        with:
          ref: master

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: packages

      - name: Git setup
        run: |
          git config --global user.name 'Boobrie'
          git config --global user.email 'boobrie@users.noreply.github.com'

      - name: Apply version update
        if: ${{ github.event_name == 'push' }}
        run: |
          yarn version apply --all

          if `git diff --quiet --exit-code`
          then
            echo "::warning::Nothing changed !"
          else
            git commit -am "chore: update bundles & version numbers"
          fi

      - name: Apply milestone version
        if: ${{ github.event_name == 'milestone' }}
        run: |
          yarn workspace @jujulego/jill version -i ${{ github.event.milestone.title }}
          yarn workspace @jujulego/jill-core version -i ${{ github.event.milestone.title }}

          if `git diff --quiet --exit-code`
          then
            echo "::warning::Nothing changed !"
          else
            git commit -am "chore: update bundles & version numbers"
            git tag ${{ github.event.milestone.title }}
          fi

      - name: Push
        run: |
          git push
          git push --tags

      - name: Publish
        run: yarn workspaces foreach --no-private npm publish --access public --tolerate-republish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages/*/package.json

  sonarcloud:
    if: ${{ !startsWith(github.head_ref, 'renovate/') }}
    runs-on: ubuntu-latest
    needs: [ publish ]

    strategy:
      fail-fast: false

      matrix:
        include:
          - name: 'jill'
            package: '@jujulego/jill'
            workspace: 'packages/cli'

          - name: 'jill-core'
            package: '@jujulego/jill-core'
            workspace: 'packages/core'

          - name: 'yarn-plugin-jill'
            package: '@jujulego/yarn-plugin-jill'
            workspace: 'packages/yarn-plugin'

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Download test coverage
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: ${{ matrix.name }}-coverage
          path: ${{ matrix.workspace }}/coverage

      - uses: actions/download-artifact@v2
        with:
          name: packages
          path: packages/*/package.json

      - name: Load package.json
        id: info
        run: 'echo ::set-output name=package::`cat ${{ matrix.workspace }}/package.json`'

      - name: Sonarcloud
        uses: sonarsource/sonarcloud-github-action@v1.6
        with:
          projectBaseDir: ${{ matrix.workspace }}
          args: >
            -Dsonar.projectVersion=${{ fromJSON(steps.info.outputs.package).version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: [publish]
    if: ${{ github.event_name == 'milestone' }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: master

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x

      - name: Setup gren
        run: npm install -g github-release-notes

      - name: Generate release
        env:
          GREN_GITHUB_TOKEN: ${{ github.token }}
        run: gren release